// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// code.cpp
int add1_(int x);
extern "C" SEXP _cpp11example1_add1_(SEXP x) {
  BEGIN_CPP11
    return cpp11::as_sexp(add1_(cpp11::as_cpp<cpp11::decay_t<int>>(x)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_cpp11example1_add1_", (DL_FUNC) &_cpp11example1_add1_, 1},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_cpp11example1(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
