# Generated by cpp11: do not edit by hand

fun <- function() {
  invisible(.Call(`_cpp11examplesep26_fun`))
}

sum_int <- function(a, b) {
  .Call(`_cpp11examplesep26_sum_int`, a, b)
}

sum_integers <- function(a, b) {
  .Call(`_cpp11examplesep26_sum_integers`, a, b)
}
