// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// code.cpp
void fun();
extern "C" SEXP _cpp11examplesep26_fun() {
  BEGIN_CPP11
    fun();
    return R_NilValue;
  END_CPP11
}
// code.cpp
int sum_int(int a, int b);
extern "C" SEXP _cpp11examplesep26_sum_int(SEXP a, SEXP b) {
  BEGIN_CPP11
    return cpp11::as_sexp(sum_int(cpp11::as_cpp<cpp11::decay_t<int>>(a), cpp11::as_cpp<cpp11::decay_t<int>>(b)));
  END_CPP11
}
// code.cpp
int sum_integers(integers a, integers b);
extern "C" SEXP _cpp11examplesep26_sum_integers(SEXP a, SEXP b) {
  BEGIN_CPP11
    return cpp11::as_sexp(sum_integers(cpp11::as_cpp<cpp11::decay_t<integers>>(a), cpp11::as_cpp<cpp11::decay_t<integers>>(b)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_cpp11examplesep26_fun",          (DL_FUNC) &_cpp11examplesep26_fun,          0},
    {"_cpp11examplesep26_sum_int",      (DL_FUNC) &_cpp11examplesep26_sum_int,      2},
    {"_cpp11examplesep26_sum_integers", (DL_FUNC) &_cpp11examplesep26_sum_integers, 2},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_cpp11examplesep26(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
