// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// code.cpp
int a_plus_b(integers a, integers b);
extern "C" SEXP _cpp11example3_a_plus_b(SEXP a, SEXP b) {
  BEGIN_CPP11
    return cpp11::as_sexp(a_plus_b(cpp11::as_cpp<cpp11::decay_t<integers>>(a), cpp11::as_cpp<cpp11::decay_t<integers>>(b)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_cpp11example3_a_plus_b", (DL_FUNC) &_cpp11example3_a_plus_b, 2},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_cpp11example3(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
